name: build
on: 
  push

jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]
    steps:
      - uses: actions/checkout@v3
      - name: my first step
        env: 
          MY_VAR: Hi there! my name is
          FIRST_NAME: Chad
          MIDDLE_NAME: Michael
          LAST_NAME: Crowell
        run: echo $MY_VAR $FIRST_NAME $LAST_NAME
      - name: my second step
        if: success()
        run: echo "The previous step has finished successfully"       
      - name: my third step
        uses: actions/checkout@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
