name: build
on: 
  push

jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [10, 12, 14]
    steps:
      - uses: actions/checkout@v3
      - name: my first step
        env: 
          MY_VAR: Hi there! my name is
          FIRST_NAME: Chad
          MIDDLE_NAME: Michael
          LAST_NAME: Crowell
        run: |
          echo $MY_VAR
          echo $FIRST_NAME
          
