name: test

on:
  pull_request:
    branches
    - master
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [12]
        os: [macos-latest, windows-latest, ubuntu-18.04]
        include:
          - node: 13
            os: ubuntu-18.04
            experimental: true
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: npm test
    
